### ISSUE TITLE
Describe how to use a private key in more depth

### ISSUE THREAD

**Issue by purplecabbage** [AdobeDocs/adobeio-samples-journaling-events#2]
The line here shows how you should format a private_key to pass to the consumer action:

https://github.com/AdobeDocs/adobeio-samples-journaling-events/blob/main/event-consumer/dot_env#L15

Users are being tripped up by this step, probably because it is not well described in the documentation.  We should add more info around the exact format of the private key new-lines, and how best to pass it through as a param to the action.

**Comment by purplecabbage** [comment]
@Yu1986 ^^ I cannot assign in this repo.

**Comment by kelvinxzf** [comment]
Please also mention double quotes are required for the private key.

**Comment by Yu1986** [comment]
I put note in the readme file and add note to the dotenv file like this, hope this will be much clear
https://github.com/AdobeDocs/adobeio-samples-journaling-events/blob/43560d1e8211fb82922ca2d489a7d8c90c6e0471/event-consumer/dot_env#L15

thanks again for pointing out @purplecabbage  and @kelvinxzf
